name: Automated Lighthouse Report

on:
  workflow_run:
    workflows: ["Deploy Next.js site to Pages"]  
    types:
      - completed

jobs:
  run-script-and-archive:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node scripts/main.mjs

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: auto_*